### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by JensMurer** [moshfeu/vscode-compare-folders#37] opened 2020-06-10 08:24 UTC
Code: 1.44.2
Compare Folders: 0.12.0

I get the message above when comparing folders, at least "only in my folder" and "only in compared folder" are not filled although I know there are differences. I don't completely trust "Differences" because of this.
It worked fine till a week ago or so.

If I can pull any logs please let me know.

**Comment by moshfeu** [comment] 2020-06-10 08:49
Thanks for the report!
That's weird. Someone else reported on a similar issue in an older version (#32) but seems like it solved somehow.
Can you try to install an older version and see if it something with the newest version (from yesterday)
![Screen Shot 2020-06-10 at 11 47 22](https://user-images.githubusercontent.com/3723951/84247068-38dc2780-ab10-11ea-8713-de60d6788085.png)

Also, isn't it working only on a specific folders pair or for any ones?

**Comment by peteamundson** [comment] 2020-06-11 16:30
I also had an error on 0.12.0 when running the `>Compare Folders: Choose 2 folders and compare` command.  Here is the message:
`Command 'Compare Folders: Choose 2 folders and compare' resulted in an error (command 'foldersCompare.compareFoldersAgainstEachOther' not found)`
I also had problems running any other type of compare (like selecting two folders and right-clicking).  This is all on VSCode v.1.46.0.

I rolled back to the 0.11.0 version and everything appears to be working.

**Comment by moshfeu** [comment] 2020-06-11 16:32
I'll check. Thanks!

**Comment by peteamundson** [comment] 2020-06-11 16:35
I don't have the diff merge extension, so maybe that is the cause?  The edits for 0.12.0 seem to try to load that extension regardless of the setting.

**Comment by moshfeu** [comment] 2020-06-11 22:40
I've just released v0.12.1. It contains a (hopefully) small fix and also, added some logs for errors. If you get an error, please go to `OUTPUT` (a sibling tab of the terminal) -> and choose `Compare Folders` from the dropdown. If there are logs there, please include them in the issue. 

Also, please include any details you can about the environment (empty workspace, only one folder, many folders) and the steps from opening the vscode instance (open a folder, run this command, add a folder to workspace etc.) the most simple the better :)

Please let me know if the errors solved.
Thank you!

**Comment by moshfeu** [comment] 2020-06-11 22:43
> I don't have the diff merge extension, so maybe that is the cause? The edits for 0.12.0 seem to try to load that extension regardless of the setting.

The usage of diff & merge is under configuration `compareFolders.useDiffMerge` and `false` [by default](https://github.com/moshfeu/vscode-compare-folders/blob/00a349a84ce0cf2be7c6e35620f1fef5e7fae07e/package.json#L102).
Only of the configuration is `true` ([here](https://github.com/moshfeu/vscode-compare-folders/blob/00a349a84ce0cf2be7c6e35620f1fef5e7fae07e/src/services/comparer.ts#L36)) and the extension been installed, it use the extension.
I also checkout with another instance of vscode which doesn't has extensions at all except compareFolders.

Can you test with [insider](https://code.visualstudio.com/insiders/)? just to make sure it's not a conflict with another extension.

**Comment by JensMurer** [comment] 2020-06-15 07:39
Hi,
the new version seems to fix the issue. I got alle differing files now.
Thank you :)

**Comment by moshfeu** [comment] 2020-06-15 13:00
Glad to hear 😀
@peteamundson what about you?

**Comment by moshfeu** [comment] 2020-06-23 07:23
I'll close it for now. @peteamundson if this happening again, please let me know.
Thanks!

**Closed by moshfeu** 2020-06-23 07:23 UTC
